CREATE TABLE `stickerss` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `text` varchar(500) COLLATE utf8mb4_unicode_ci NOT NULL,
  `language_code` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
  `priority` int(10) UNSIGNED NOT NULL DEFAULT '1',
  `start_hour` tinyint(3) UNSIGNED DEFAULT NULL,
  `end_hour` tinyint(3) UNSIGNED DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `font_sticker_default_texts`
--

INSERT INTO `stickerss` (`id`, `text`, `language_code`, `priority`, `start_hour`, `end_hour`, `created_at`, `updated_at`) VALUES
(1, 'Hi', 'en', 1, NULL, NULL, NULL, NULL),
(2, 'Good morning', 'en', 2, 4, 12, NULL, NULL),
(3, 'Good afternoon', 'en', 2, 12, 16, NULL, NULL),
(4, 'Good evening', 'en', 2, 16, 20, NULL, NULL),
(5, 'Good night', 'en', 2, 20, 24, NULL, NULL),
(6, 'Good night', 'en', 2, 0, 4, NULL, NULL),
(7, 'Thank you', 'en', 3, NULL, NULL, NULL, NULL),
(8, 'I love you', 'en', 4, NULL, NULL, NULL, NULL),
(9, 'Sorry', 'en', 5, NULL, NULL, NULL, NULL),
(10, 'Bye', 'en', 6, NULL, NULL, NULL, NULL),
(11, 'Happy birthday', 'en', 7, NULL, NULL, NULL, NULL),
(12, 'I miss you', 'en', 8, NULL, NULL, NULL, NULL),
(13, 'Please', 'en', 9, NULL, NULL, NULL, NULL),
(14, 'Yes', 'en', 10, NULL, NULL, NULL, NULL),
(15, 'नमस्ते', 'hi', 1, NULL, NULL, NULL, NULL),
(16, 'गुड मॉर्निंग', 'hi', 2, 4, 12, NULL, NULL),
(17, 'गुड आफ्टरनून', 'hi', 2, 12, 16, NULL, NULL),
(18, 'गुड ईवनिंग', 'hi', 2, 16, 20, NULL, NULL),
(19, 'गुड नाइट', 'hi', 2, 20, 24, NULL, NULL),
(20, 'गुड नाइट', 'hi', 2, 0, 4, NULL, NULL),
(21, 'धन्यवाद', 'hi', 3, NULL, NULL, NULL, NULL),
(22, 'मैं तुमसे प्यार करता हूं', 'hi', 4, NULL, NULL, NULL, NULL),
(23, 'माफ़ करें', 'hi', 5, NULL, NULL, NULL, NULL),
(24, 'अलविदा', 'hi', 6, NULL, NULL, NULL, NULL),
(25, 'जन्मदिन मुबारक हो', 'hi', 7, NULL, NULL, NULL, NULL),
(26, 'मुझे तुम्हारी याद आ रही है', 'hi', 8, NULL, NULL, NULL, NULL),
(27, 'कृपया', 'hi', 9, NULL, NULL, NULL, NULL),
(28, 'हां', 'hi', 10, NULL, NULL, NULL, NULL),
(29, 'ହାଏ', 'or', 1, NULL, NULL, NULL, NULL),
(30, 'ଶୁଭ ସକାଳ', 'or', 2, 4, 12, NULL, NULL),
(31, 'ଶୁଭ ମଧ୍ୟାହ୍ନ', 'or', 2, 12, 16, NULL, NULL),
(32, 'ଶୁଭ ସନ୍ଧ୍ୟା', 'or', 2, 16, 20, NULL, NULL),
(33, 'ଶୁଭ ରାତ୍ରି', 'or', 2, 20, 24, NULL, NULL),
(34, 'ଶୁଭ ରାତ୍ରି', 'or', 2, 0, 4, NULL, NULL),
(35, 'ଧନ୍ୟବାଦ', 'or', 3, NULL, NULL, NULL, NULL),
(36, 'ମୁଁ ତୁମକୁ ଭଲପାଏଁ', 'or', 4, NULL, NULL, NULL, NULL),
(37, 'ଦୁଃଖିତ', 'or', 5, NULL, NULL, NULL, NULL),
(38, 'ବିଦାୟ', 'or', 6, NULL, NULL, NULL, NULL),
(39, 'ଜନ୍ମଦିନର ଶୁଭେଚ୍ଛା', 'or', 7, NULL, NULL, NULL, NULL),
(40, 'ତୁମକୁ ବହୁତ ମିସ୍ କରେ', 'or', 8, NULL, NULL, NULL, NULL),
(41, 'ଦୟାକରି', 'or', 9, NULL, NULL, NULL, NULL),
(42, 'ହଁ', 'or', 10, NULL, NULL, NULL, NULL),
(43, 'ಹಾಯ್', 'kn', 1, NULL, NULL, NULL, NULL),
(44, 'ಶುಭೋದಯ', 'kn', 2, 4, 12, NULL, NULL),
(45, 'ಶುಭ ಮಧ್ಯಾಹ್ನ', 'kn', 2, 12, 16, NULL, NULL),
(46, 'ಶುಭ ಸಂಜೆ', 'kn', 2, 16, 20, NULL, NULL),
(47, 'ಶುಭ ರಾತ್ರಿ', 'kn', 2, 20, 24, NULL, NULL),
(48, 'ಶುಭ ರಾತ್ರಿ', 'kn', 2, 0, 4, NULL, NULL),
(49, 'ಧನ್ಯವಾದಗಳು', 'kn', 3, NULL, NULL, NULL, NULL),
(50, 'ನಾನು ನಿನ್ನನ್ನು ಪ್ರೀತಿಸುತ್ತೇನೆ', 'kn', 4, NULL, NULL, NULL, NULL),
(51, 'ಕ್ಷಮಿಸಿ', 'kn', 5, NULL, NULL, NULL, NULL),
(52, 'ಬೈ', 'kn', 6, NULL, NULL, NULL, NULL),
(53, 'ಜನ್ಮದಿನದ ಶುಭಾಶಯಗಳು', 'kn', 7, NULL, NULL, NULL, NULL),
(54, 'ನಿನ್ನ ಮಿಸ್‌ ಮಾಡ್ಕೋತಿದೀನಿ', 'kn', 8, NULL, NULL, NULL, NULL),
(55, 'ಪ್ಲೀಸ್‌', 'kn', 9, NULL, NULL, NULL, NULL),
(56, 'ಹೌದು', 'kn', 10, NULL, NULL, NULL, NULL),
(57, 'हाय', 'mr', 1, NULL, NULL, NULL, NULL),
(58, 'गुड मॉर्निंग', 'mr', 2, 4, 12, NULL, NULL),
(59, 'गुड आफ्टरनून', 'mr', 2, 12, 16, NULL, NULL),
(60, 'गुड इव्हनिंग', 'mr', 2, 16, 20, NULL, NULL),
(61, 'गुड नाईट', 'mr', 2, 20, 24, NULL, NULL),
(62, 'गुड नाईट', 'mr', 2, 0, 4, NULL, NULL),
(63, 'धन्यवाद', 'mr', 3, NULL, NULL, NULL, NULL),
(64, 'आय लव्ह यू', 'mr', 4, NULL, NULL, NULL, NULL),
(65, 'माफ करा', 'mr', 5, NULL, NULL, NULL, NULL),
(66, 'बाय', 'mr', 6, NULL, NULL, NULL, NULL),
(67, 'जन्मदिवसाच्या शुभेच्छा', 'mr', 7, NULL, NULL, NULL, NULL),
(68, 'आय मिस यू', 'mr', 8, NULL, NULL, NULL, NULL),
(69, 'कृपया', 'mr', 9, NULL, NULL, NULL, NULL),
(70, 'होय', 'mr', 10, NULL, NULL, NULL, NULL),
(71, 'হাই', 'bn', 1, NULL, NULL, NULL, NULL),
(72, 'শুপ্রভাত', 'bn', 2, 4, 12, NULL, NULL),
(73, 'শুভ মধ্যান্য', 'bn', 2, 12, 16, NULL, NULL),
(74, 'শুভ সন্ধ্যা', 'bn', 2, 16, 20, NULL, NULL),
(75, 'শুভ রাত্রি', 'bn', 2, 20, 24, NULL, NULL),
(76, 'শুভ রাত্রি', 'bn', 2, 0, 4, NULL, NULL),
(77, 'ধন্যবাদ', 'bn', 3, NULL, NULL, NULL, NULL),
(78, 'আমি তোমাকে ভালবাসি', 'bn', 4, NULL, NULL, NULL, NULL),
(79, 'দুঃখিত', 'bn', 5, NULL, NULL, NULL, NULL),
(80, 'বিদায়', 'bn', 6, NULL, NULL, NULL, NULL),
(81, 'শুভ জন্মদিন', 'bn', 7, NULL, NULL, NULL, NULL),
(82, 'তোমায় খুব মিস করছি', 'bn', 8, NULL, NULL, NULL, NULL),
(83, 'অনুগ্রহ করে', 'bn', 9, NULL, NULL, NULL, NULL),
(84, 'হ্যাঁ', 'bn', 10, NULL, NULL, NULL, NULL),
(85, 'નમસ્તે', 'gu', 1, NULL, NULL, NULL, NULL),
(86, 'સુપ્રભાત', 'gu', 2, 4, 12, NULL, NULL),
(87, 'શુભ બપોર', 'gu', 2, 12, 16, NULL, NULL),
(88, 'શુભ સાંજ', 'gu', 2, 16, 20, NULL, NULL),
(89, 'શુભ રાત્રી', 'gu', 2, 20, 24, NULL, NULL),
(90, 'શુભ રાત્રી', 'gu', 2, 0, 4, NULL, NULL),
(91, 'આપનો આભાર', 'gu', 3, NULL, NULL, NULL, NULL),
(92, 'હું તને પ્રેમ કરું છુ', 'gu', 4, NULL, NULL, NULL, NULL),
(93, 'માફ કરશો', 'gu', 5, NULL, NULL, NULL, NULL),
(94, 'બાય', 'gu', 6, NULL, NULL, NULL, NULL),
(95, 'હેપ્પી બર્થડે', 'gu', 7, NULL, NULL, NULL, NULL),
(96, 'હું તને યાદ કરું છું', 'gu', 8, NULL, NULL, NULL, NULL),
(97, 'પ્લીઝ', 'gu', 9, NULL, NULL, NULL, NULL),
(98, 'હા', 'gu', 10, NULL, NULL, NULL, NULL),
(99, 'آداب', 'ur', 1, NULL, NULL, NULL, NULL),
(100, 'صبح بخیر', 'ur', 2, 4, 12, NULL, NULL),
(101, 'سہ پہر بخیر', 'ur', 2, 12, 16, NULL, NULL),
(102, 'شام بخیر', 'ur', 2, 16, 20, NULL, NULL),
(103, 'شب بخیر', 'ur', 2, 20, 24, NULL, NULL),
(104, 'شب بخیر', 'ur', 2, 0, 4, NULL, NULL),
(105, 'آپ کا شکریہ', 'ur', 3, NULL, NULL, NULL, NULL),
(106, 'مجھے تم سے پیار ہے', 'ur', 4, NULL, NULL, NULL, NULL),
(107, 'معاف کریں', 'ur', 5, NULL, NULL, NULL, NULL),
(108, 'الوداع', 'ur', 6, NULL, NULL, NULL, NULL),
(109, 'یوم پیدائش مبارک', 'ur', 7, NULL, NULL, NULL, NULL),
(110, 'مجھے تمھاری یاد آ رہی ہے', 'ur', 8, NULL, NULL, NULL, NULL),
(111, 'براہ کرم', 'ur', 9, NULL, NULL, NULL, NULL),
(112, 'ہاں', 'ur', 10, NULL, NULL, NULL, NULL),
(113, 'নমস্কাৰ', 'as', 1, NULL, NULL, NULL, NULL),
(114, 'সুপ্ৰভাত', 'as', 2, 4, 12, NULL, NULL),
(115, 'শুভ-আবেলি', 'as', 2, 12, 16, NULL, NULL),
(116, 'শুভ-সন্ধ্যা', 'as', 2, 16, 20, NULL, NULL),
(117, 'শুভৰাত্ৰি', 'as', 2, 20, 24, NULL, NULL),
(118, 'শুভৰাত্ৰি', 'as', 2, 0, 4, NULL, NULL),
(119, 'ধন্যবাদ', 'as', 3, NULL, NULL, NULL, NULL),
(120, 'মই তোমাক ভাল পাও', 'as', 4, NULL, NULL, NULL, NULL),
(121, 'দুখিত', 'as', 5, NULL, NULL, NULL, NULL),
(122, 'বিদায়', 'as', 6, NULL, NULL, NULL, NULL),
(123, 'শুভ জন্মদিন', 'as', 7, NULL, NULL, NULL, NULL),
(124, 'মোৰ তোমালৈ মনত পৰিছে', 'as', 8, NULL, NULL, NULL, NULL),
(125, 'দয়া কৰি', 'as', 9, NULL, NULL, NULL, NULL),
(126, 'হয়', 'as', 10, NULL, NULL, NULL, NULL),
(127, 'Hi', 'hr', 1, NULL, NULL, NULL, NULL),
(128, 'Good morning', 'hr', 2, 4, 12, NULL, NULL),
(129, 'Good afternoon', 'hr', 2, 12, 16, NULL, NULL),
(130, 'Good evening', 'hr', 2, 16, 20, NULL, NULL),
(131, 'Good night', 'hr', 2, 20, 24, NULL, NULL),
(132, 'Good night', 'hr', 2, 0, 4, NULL, NULL),
(133, 'Thank you', 'hr', 3, NULL, NULL, NULL, NULL),
(134, 'I love you', 'hr', 4, NULL, NULL, NULL, NULL),
(135, 'Sorry', 'hr', 5, NULL, NULL, NULL, NULL),
(136, 'Bye', 'hr', 6, NULL, NULL, NULL, NULL),
(137, 'Happy birthday', 'hr', 7, NULL, NULL, NULL, NULL),
(138, 'I miss you', 'hr', 8, NULL, NULL, NULL, NULL),
(139, 'Please', 'hr', 9, NULL, NULL, NULL, NULL),
(140, 'Yes', 'hr', 10, NULL, NULL, NULL, NULL),
(141, 'Hai', 'in', 1, NULL, NULL, NULL, NULL),
(142, 'Selamat pagi', 'in', 2, 4, 12, NULL, NULL),
(143, 'Selamat siang', 'in', 2, 12, 16, NULL, NULL),
(144, 'Selamat sore', 'in', 2, 16, 20, NULL, NULL),
(145, 'Selamat malam', 'in', 2, 20, 24, NULL, NULL),
(146, 'Selamat malam', 'in', 2, 0, 4, NULL, NULL),
(147, 'Terima kasih', 'in', 3, NULL, NULL, NULL, NULL),
(148, 'Aku cinta kamu', 'in', 4, NULL, NULL, NULL, NULL),
(149, 'Maaf', 'in', 5, NULL, NULL, NULL, NULL),
(150, 'Sampai jumpa', 'in', 6, NULL, NULL, NULL, NULL),
(151, 'Selamat Ulang tahun', 'in', 7, NULL, NULL, NULL, NULL),
(152, 'Aku kangen kamu', 'in', 8, NULL, NULL, NULL, NULL),
(153, 'Tolong', 'in', 9, NULL, NULL, NULL, NULL),
(154, 'Ya', 'in', 10, NULL, NULL, NULL, NULL),
(155, 'హాయ్', 'te', 1, NULL, NULL, NULL, NULL),
(156, 'శుభోదయం', 'te', 2, 4, 12, NULL, NULL),
(157, 'శుభ మధ్యాహ్నం', 'te', 2, 12, 16, NULL, NULL),
(158, 'శుభ సాయంత్రం', 'te', 2, 16, 20, NULL, NULL),
(159, 'శుభరాత్రి', 'te', 2, 20, 24, NULL, NULL),
(160, 'శుభరాత్రి', 'te', 2, 0, 4, NULL, NULL),
(161, 'ధన్యవాదాలు', 'te', 3, NULL, NULL, NULL, NULL),
(162, 'నేను నిన్ను ప్రేమిస్తున్నాను', 'te', 4, NULL, NULL, NULL, NULL),
(163, 'క్షమించండి', 'te', 5, NULL, NULL, NULL, NULL),
(164, 'బై', 'te', 6, NULL, NULL, NULL, NULL),
(165, 'పుట్టినరోజు శుభాకాంక్షలు', 'te', 7, NULL, NULL, NULL, NULL),
(166, 'నేను నిన్ను మిస్ అవుతున్నాను', 'te', 8, NULL, NULL, NULL, NULL),
(167, 'క్షమించండి', 'te', 9, NULL, NULL, NULL, NULL),
(168, 'అవును', 'te', 10, NULL, NULL, NULL, NULL),
(169, 'ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ', 'pa', 1, NULL, NULL, NULL, NULL),
(170, 'ਗੁੱਡ ਮੋਰਨਿੰਗ', 'pa', 2, 4, 12, NULL, NULL),
(171, 'ਗੁੱਡ ਆਫ਼ਟਰਨੂਨ', 'pa', 2, 12, 16, NULL, NULL),
(172, 'ਗੁੱਡ ਈਵਨਿੰਗ', 'pa', 2, 16, 20, NULL, NULL),
(173, 'ਗੁੱਡ ਨਾਈਟ', 'pa', 2, 20, 24, NULL, NULL),
(174, 'ਗੁੱਡ ਨਾਈਟ', 'pa', 2, 0, 4, NULL, NULL),
(175, 'ਤੁਹਾਡਾ ਧੰਨਵਾਦ', 'pa', 3, NULL, NULL, NULL, NULL),
(176, 'ਮੈਂ ਤੁਹਾਨੂੰ ਪਿਆਰ ਕਰਦਾ/ਕਰਦੀ ਹਾਂ', 'pa', 4, NULL, NULL, NULL, NULL),
(177, 'ਮਾਫ਼ ਕਰਨਾ', 'pa', 5, NULL, NULL, NULL, NULL),
(178, 'ਅਲਵਿਦਾ', 'pa', 6, NULL, NULL, NULL, NULL),
(179, 'ਜਨਮਦਿਨ ਮੁਬਾਰਕ', 'pa', 7, NULL, NULL, NULL, NULL),
(180, 'ਮੈਨੂੰ ਤੁਹਾਡੀ ਯਾਦ ਆਉਂਦੀ ਹੈ', 'pa', 8, NULL, NULL, NULL, NULL),
(181, 'ਕਿਰਪਾ ਕਰਕੇ', 'pa', 9, NULL, NULL, NULL, NULL),
(182, 'ਹਾਂ', 'pa', 10, NULL, NULL, NULL, NULL),
(183, 'ഹായ്', 'ml', 1, NULL, NULL, NULL, NULL),
(184, 'ഗുഡ് മോണിംഗ്', 'ml', 2, 4, 12, NULL, NULL),
(185, 'ഗുഡ് ആഫ്റ്റർനൂൺ', 'ml', 2, 12, 16, NULL, NULL),
(186, 'ഗുഡ് ഈവനിംഗ്', 'ml', 2, 16, 20, NULL, NULL),
(187, 'ഗുഡ് നൈറ്റ്', 'ml', 2, 20, 24, NULL, NULL),
(188, 'ഗുഡ് നൈറ്റ്', 'ml', 2, 0, 4, NULL, NULL),
(189, 'നന്ദി', 'ml', 3, NULL, NULL, NULL, NULL),
(190, 'ഞാൻ നിന്നെ സ്നേഹിക്കുന്നു', 'ml', 4, NULL, NULL, NULL, NULL),
(191, 'ക്ഷമിക്കണം', 'ml', 5, NULL, NULL, NULL, NULL),
(192, 'ബൈ', 'ml', 6, NULL, NULL, NULL, NULL),
(193, 'ജന്മദിനാശംസകൾ', 'ml', 7, NULL, NULL, NULL, NULL),
(194, 'എനിക്ക് നിങ്ങളെ മിസ് ആകുന്നു', 'ml', 8, NULL, NULL, NULL, NULL),
(195, 'ദയവായി', 'ml', 9, NULL, NULL, NULL, NULL),
(196, 'ഉവ്വ്', 'ml', 10, NULL, NULL, NULL, NULL),
(197, 'Salom', 'uz', 1, NULL, NULL, NULL, NULL),
(198, 'Xayrli tong', 'uz', 2, 4, 12, NULL, NULL),
(199, 'Xayrli kun', 'uz', 2, 12, 16, NULL, NULL),
(200, 'Xayrli kech', 'uz', 2, 16, 20, NULL, NULL),
(201, 'Xayrli tun', 'uz', 2, 20, 24, NULL, NULL),
(202, 'Xayrli tun', 'uz', 2, 0, 4, NULL, NULL),
(203, 'Rahmat', 'uz', 3, NULL, NULL, NULL, NULL),
(204, 'Men seni sevaman', 'uz', 4, NULL, NULL, NULL, NULL),
(205, 'Kechirasiz', 'uz', 5, NULL, NULL, NULL, NULL),
(206, 'Xayr', 'uz', 6, NULL, NULL, NULL, NULL),
(207, 'Tug‘ilgan kuning bilan', 'uz', 7, NULL, NULL, NULL, NULL),
(208, 'Sizni sog‘indim', 'uz', 8, NULL, NULL, NULL, NULL),
(209, 'Iltimos', 'uz', 9, NULL, NULL, NULL, NULL),
(210, 'Ha', 'uz', 10, NULL, NULL, NULL, NULL),
(211, 'नमस्ते', 'ne', 1, NULL, NULL, NULL, NULL),
(212, 'शुप्रभात', 'ne', 2, 4, 12, NULL, NULL),
(213, 'शुभ मध्यान्न', 'ne', 2, 12, 16, NULL, NULL),
(214, 'शुभ सन्ध्या', 'ne', 2, 16, 20, NULL, NULL),
(215, 'शुभ रात्री', 'ne', 2, 20, 24, NULL, NULL),
(216, 'शुभ रात्री', 'ne', 2, 0, 4, NULL, NULL),
(217, 'धन्यवाद', 'ne', 3, NULL, NULL, NULL, NULL),
(218, 'म तिमीलाई माया गर्छु', 'ne', 4, NULL, NULL, NULL, NULL),
(219, 'माफ गर्नुहोस्', 'ne', 5, NULL, NULL, NULL, NULL),
(220, 'बिदा दिनुहोस्', 'ne', 6, NULL, NULL, NULL, NULL),
(221, 'जन्मदिनको शुभकामना', 'ne', 7, NULL, NULL, NULL, NULL),
(222, 'म तिमीलाई सम्झिन्छु', 'ne', 8, NULL, NULL, NULL, NULL),
(223, 'कृपा गरी', 'ne', 9, NULL, NULL, NULL, NULL),
(224, 'हजुर', 'ne', 10, NULL, NULL, NULL, NULL),
(225, 'ஹாய்', 'ta', 1, NULL, NULL, NULL, NULL),
(226, 'காலை வணக்கம்', 'ta', 2, 4, 12, NULL, NULL),
(227, 'மதிய வணக்கம்', 'ta', 2, 12, 16, NULL, NULL),
(228, 'மாலை வணக்கம்', 'ta', 2, 16, 20, NULL, NULL),
(229, 'இரவு வணக்கம்', 'ta', 2, 20, 24, NULL, NULL),
(230, 'இரவு வணக்கம்', 'ta', 2, 0, 4, NULL, NULL),
(231, 'நன்றி', 'ta', 3, NULL, NULL, NULL, NULL),
(232, 'ஐ லவ் யூ', 'ta', 4, NULL, NULL, NULL, NULL),
(233, 'மன்னிக்கவும்', 'ta', 5, NULL, NULL, NULL, NULL),
(234, 'பை பை', 'ta', 6, NULL, NULL, NULL, NULL),
(235, 'பிறந்த நாள் வாழ்த்துகள்', 'ta', 7, NULL, NULL, NULL, NULL),
(236, 'ஐ மிஸ் யூ', 'ta', 8, NULL, NULL, NULL, NULL),
(237, 'ப்ளீஸ்', 'ta', 9, NULL, NULL, NULL, NULL),
(238, 'ஆம்', 'ta', 10, NULL, NULL, NULL, NULL),
(239, 'Oi', 'pt', 1, NULL, NULL, NULL, NULL),
(240, 'Bom dia', 'pt', 2, 4, 12, NULL, NULL),
(241, 'Boa tarde', 'pt', 2, 12, 16, NULL, NULL),
(242, 'Boa noite', 'pt', 2, 16, 20, NULL, NULL),
(243, 'Boa noite', 'pt', 2, 20, 24, NULL, NULL),
(244, 'Boa noite', 'pt', 2, 0, 4, NULL, NULL),
(245, 'Obrigado', 'pt', 3, NULL, NULL, NULL, NULL),
(246, 'Eu te amo', 'pt', 4, NULL, NULL, NULL, NULL),
(247, 'Desculpe', 'pt', 5, NULL, NULL, NULL, NULL),
(248, 'Tchau', 'pt', 6, NULL, NULL, NULL, NULL),
(249, 'Feliz aniversário', 'pt', 7, NULL, NULL, NULL, NULL),
(250, 'Sinto sua falta', 'pt', 8, NULL, NULL, NULL, NULL),
(251, 'Por favor', 'pt', 9, NULL, NULL, NULL, NULL),
(252, 'Sim', 'pt', 10, NULL, NULL, NULL, NULL);
